project:
  type: website
  output-dir: docs

website:
  title: "My sparse website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: projects.qmd
      - href: aplications.qmd
        text: Aplications
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



